kind: Service
apiVersion: v1
metadata:
  name: ngservice-c-public
  namespace: nms-capacitacion
  labels:
    app: ngservice-c
spec:
  type: NodePort
  selector:
    app: ngservice-c
  ports:
    - nodePort: 30603
      port: 80
      protocol: TCP
      targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ngservice-c
  namespace: nms-capacitacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngservice-c
  template:
    metadata:
      labels:
        app: ngservice-c
        version: v1
    spec:
      containers:
        - name: ngservice-c
          image: gian411/ngservice-c:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
