kind: Service
apiVersion: v1
metadata:
  name: jservice-b
  namespace: nms-capacitacion
  labels:
    app: jservice-b
spec:
  type: ClusterIP
  selector:
    app: jservice-b
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: jservice-b-public
  namespace: nms-capacitacion
  labels:
    app: jservice-b-public
spec:
  type: NodePort
  selector:
    app: jservice-b
  ports:
    - nodePort: 30602
      port: 80
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jservice-b
  namespace: nms-capacitacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jservice-b
  template:
    metadata:
      labels:
        app: jservice-b
        version: v1
    spec:
      containers:
      - name: jservice-b
        image: gian411/jservice-b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
